# Generated by Django 5.0.4 on 2024-04-23 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinderapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='saw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isseen', models.CharField(default='not_seen', max_length=100)),
                ('colors', models.CharField(default='#FA7070', max_length=100)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinderapp.postupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
